build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
              override:
                - php-scrutinizer-run
                - js-scrutinizer-run

    environment:
      php: 7.4.0

filter:
    excluded_paths:
      - 'js/jquery*'

imports:
    - javascript
    - php