tools:
    php_codesniffer:
        config:
            standard: WordPress
build:
    environment:
        php:
            version: 7.3
    dependencies:
        before:
            - composer require --dev johnpbloch/wordpress
            - composer require --dev dealerdirect/phpcodesniffer-composer-installer
            - composer require --dev squizlabs/php_codesniffer
            - composer require --dev wp-coding-standards/wpcs
            - composer install --prefer-dist --no-suggest
    nodes:
        analysis:
            cache:
                directories:
                    - vendor/        
            tests:
                override:
                    - php-scrutinizer-run
                    - js-scrutinizer-run
checks:
checks:
    php:
        # enable the PHP analysis
        enabled: true
        # run the PHP CS Fixer command before analyzing the code
        before_commands:
          - composer install
        #  - vendor/bin/php-cs-fixer fix
        # run the PHP_CodeSniffer command to check for coding standards violations
        override:
          - vendor/bin/phpcs --standard=WordPress

            #    php:
            #        avoid_closing_tag: false
            #        avoid_superglobals: false
            #        no_exit: false
            #        psr2_control_structure_declaration: false
            #        variable_existence: false
            #        verify_access_scope_valid: false
            #        verify_argument_usable_as_reference: false
            #        verify_property_names: false
            #        fix_php_opening_tag: false
            #        remove_php_closing_tag: false
            #        no_mixed_inline_html: false
            #        require_braces_around_control_structures: false
            #        security_vulnerabilities: false
            #        coding_standard:
            #            name: WordPress
    javascript: true
filter:
    paths:
        - ./
    excluded_paths:
        - wpcs/
        - vendor/
    dependency_paths:
        - wordpress/
        - vendor/
imports:
    - javascript
    - php
        
