name: Generate changelog
on:
  workflow_dispatch: 
#  push:
  
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
#    - uses: BobAnkh/auto-generate-changelog@master
#      with:
#        REPO_NAME: 'ymichel/Geolocation-Plugin'
#        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
#        PATH: 'CHANGELOG.md'
#        COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
#        TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
##        UNRELEASED_COMMITS: true
##        REGENERATE_COUNT: -1
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md          
